using FluentAssertions;
using Moq;
using TestingPlayground.Advanced.Checkout;
using Xunit;

namespace TestingPlayground.Tests.Advanced.Checkout;

public class CheckoutServiceTests
{
    private static readonly Guid CustomerId = Guid.Parse("11111111-1111-1111-1111-111111111111");

    private static readonly CartItem Keyboard =
        new(Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"), "Teclado", 50.00m, 2);

    private static readonly CartItem Mouse =
        new(Guid.Parse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"), "Mouse", 25.50m, 1);

    // 50.00 x 2 + 25.50 x 1
    private const decimal CartTotal = 125.50m;

    private readonly Mock<IInventoryService> _inventory = new();
    private readonly Mock<IPaymentGateway> _payment = new();
    private readonly Mock<IOrderRepository> _orders = new();
    private readonly Mock<INotificationService> _notifications = new();
    private readonly CheckoutService _service;

    public CheckoutServiceTests()
    {
        _service = new CheckoutService(
            _inventory.Object,
            _payment.Object,
            _orders.Object,
            _notifications.Object);
    }

    // ---------- Successful checkout ----------

    [Fact]
    public async Task CheckoutAsync_ValidCart_ChargesTotalSavesAndNotifies()
    {
        GivenAllProductsInStock();
        GivenPaymentSucceeds(true);
        Order? savedOrder = null;
        _orders
            .Setup(orders => orders.SaveAsync(It.IsAny<Order>()))
            .Callback<Order>(order => savedOrder = order)
            .Returns(Task.CompletedTask);

        var result = await _service.CheckoutAsync(CustomerId, new[] { Keyboard, Mouse });

        result.Total.Should().Be(CartTotal);
        savedOrder.Should().BeSameAs(result);

        _inventory.Verify(inventory => inventory.HasStockAsync(Keyboard.ProductId, 2), Times.Once);
        _inventory.Verify(inventory => inventory.HasStockAsync(Mouse.ProductId, 1), Times.Once);
        _inventory.Verify(inventory => inventory.HasStockAsync(It.IsAny<Guid>(), It.IsAny<int>()), Times.Exactly(2));
        _payment.Verify(
            payment => payment.ChargeAsync(CustomerId, It.Is<decimal>(amount => amount == CartTotal)),
            Times.Once);
        _orders.Verify(orders => orders.SaveAsync(It.IsAny<Order>()), Times.Once);
        _notifications.Verify(notifications => notifications.SendOrderConfirmationAsync(result), Times.Once);
    }

    [Fact]
    public async Task CheckoutAsync_ValidCart_ReturnsOrderWithCartContents()
    {
        GivenAllProductsInStock();
        GivenPaymentSucceeds(true);

        var result = await _service.CheckoutAsync(CustomerId, new[] { Keyboard, Mouse });

        // Object graph comparison; Id is generated by the service so it is excluded.
        result.Should().BeEquivalentTo(
            new Order(Guid.Empty, CustomerId, new[] { Keyboard, Mouse }, CartTotal),
            options => options.Excluding(order => order.Id));
        result.Id.Should().NotBeEmpty();
    }

    [Fact]
    public async Task CheckoutAsync_ValidCart_SavesOrderBeforeSendingConfirmation()
    {
        GivenAllProductsInStock();
        GivenPaymentSucceeds(true);
        var calls = new List<string>();
        _orders
            .Setup(orders => orders.SaveAsync(It.IsAny<Order>()))
            .Callback(() => calls.Add("save"))
            .Returns(Task.CompletedTask);
        _notifications
            .Setup(notifications => notifications.SendOrderConfirmationAsync(It.IsAny<Order>()))
            .Callback(() => calls.Add("notify"))
            .Returns(Task.CompletedTask);

        await _service.CheckoutAsync(CustomerId, new[] { Keyboard, Mouse });

        calls.Should().Equal("save", "notify");
    }

    [Fact]
    public async Task CheckoutAsync_CartModifiedAfterCheckout_DoesNotChangeOrderItems()
    {
        GivenAllProductsInStock();
        GivenPaymentSucceeds(true);
        var cart = new List<CartItem> { Keyboard };

        var result = await _service.CheckoutAsync(CustomerId, cart);
        cart.Add(Mouse);

        result.Items.Should().ContainSingle().Which.Should().Be(Keyboard);
    }

    [Fact]
    public async Task CheckoutAsync_FreeItem_IsAllowedAndChargesZero()
    {
        GivenAllProductsInStock();
        GivenPaymentSucceeds(true);
        var freeSticker = new CartItem(Guid.NewGuid(), "Sticker", 0m, 3);

        var result = await _service.CheckoutAsync(CustomerId, new[] { freeSticker });

        result.Total.Should().Be(0m);
        _payment.Verify(payment => payment.ChargeAsync(CustomerId, 0m), Times.Once);
    }

    // ---------- Invalid cart: nothing external may be touched ----------

    [Fact]
    public async Task CheckoutAsync_NullCart_ThrowsArgumentNullException()
    {
        Func<Task> act = () => _service.CheckoutAsync(CustomerId, null!);

        await act.Should().ThrowAsync<ArgumentNullException>().WithParameterName("items");
        VerifyNoExternalCallsWereMade();
    }

    [Fact]
    public async Task CheckoutAsync_EmptyCart_ThrowsArgumentException()
    {
        Func<Task> act = () => _service.CheckoutAsync(CustomerId, Array.Empty<CartItem>());

        await act.Should().ThrowAsync<ArgumentException>()
            .WithParameterName("items")
            .WithMessage("*empty*");
        VerifyNoExternalCallsWereMade();
    }

    [Theory]
    [InlineData(0)]
    [InlineData(-1)]
    public async Task CheckoutAsync_QuantityNotPositive_ThrowsArgumentException(int quantity)
    {
        var invalidItem = Mouse with { Quantity = quantity };

        Func<Task> act = () => _service.CheckoutAsync(CustomerId, new[] { Keyboard, invalidItem });

        await act.Should().ThrowAsync<ArgumentException>().WithMessage("*Quantity*Mouse*");
        VerifyNoExternalCallsWereMade();
    }

    [Fact]
    public async Task CheckoutAsync_NegativeUnitPrice_ThrowsArgumentException()
    {
        var invalidItem = Mouse with { UnitPrice = -0.01m };

        Func<Task> act = () => _service.CheckoutAsync(CustomerId, new[] { invalidItem });

        await act.Should().ThrowAsync<ArgumentException>().WithMessage("*price*Mouse*");
        VerifyNoExternalCallsWereMade();
    }

    // ---------- Stock ----------

    [Fact]
    public async Task CheckoutAsync_ProductOutOfStock_StopsBeforePayment()
    {
        _inventory.Setup(inventory => inventory.HasStockAsync(Keyboard.ProductId, Keyboard.Quantity)).ReturnsAsync(true);
        _inventory.Setup(inventory => inventory.HasStockAsync(Mouse.ProductId, Mouse.Quantity)).ReturnsAsync(false);

        Func<Task> act = () => _service.CheckoutAsync(CustomerId, new[] { Keyboard, Mouse });

        await act.Should().ThrowAsync<InvalidOperationException>().WithMessage("*stock*Mouse*");
        _payment.Verify(payment => payment.ChargeAsync(It.IsAny<Guid>(), It.IsAny<decimal>()), Times.Never);
        _orders.Verify(orders => orders.SaveAsync(It.IsAny<Order>()), Times.Never);
        _notifications.Verify(notifications => notifications.SendOrderConfirmationAsync(It.IsAny<Order>()), Times.Never);
    }

    [Fact]
    public async Task CheckoutAsync_FirstProductOutOfStock_DoesNotCheckRemainingProducts()
    {
        _inventory.Setup(inventory => inventory.HasStockAsync(Keyboard.ProductId, It.IsAny<int>())).ReturnsAsync(false);

        Func<Task> act = () => _service.CheckoutAsync(CustomerId, new[] { Keyboard, Mouse });

        await act.Should().ThrowAsync<InvalidOperationException>();
        _inventory.Verify(inventory => inventory.HasStockAsync(Mouse.ProductId, It.IsAny<int>()), Times.Never);
    }

    // ---------- Payment ----------

    [Fact]
    public async Task CheckoutAsync_PaymentRejected_DoesNotSaveOrNotify()
    {
        GivenAllProductsInStock();
        GivenPaymentSucceeds(false);
        Order? savedOrder = null;
        _orders
            .Setup(orders => orders.SaveAsync(It.IsAny<Order>()))
            .Callback<Order>(order => savedOrder = order);

        Func<Task> act = () => _service.CheckoutAsync(CustomerId, new[] { Keyboard, Mouse });

        await act.Should().ThrowAsync<InvalidOperationException>().WithMessage("*payment*rejected*");
        _payment.Verify(
            payment => payment.ChargeAsync(CustomerId, It.Is<decimal>(amount => amount == CartTotal)),
            Times.Once);
        _orders.Verify(orders => orders.SaveAsync(It.IsAny<Order>()), Times.Never);
        _notifications.Verify(notifications => notifications.SendOrderConfirmationAsync(It.IsAny<Order>()), Times.Never);

        // Capture-based view of the same fact as the Times.Never above.
        Assert.Null(savedOrder);
    }

    [Fact]
    public async Task CheckoutAsync_PaymentGatewayFails_PropagatesExceptionWithoutSaving()
    {
        GivenAllProductsInStock();
        _payment
            .Setup(payment => payment.ChargeAsync(It.IsAny<Guid>(), It.IsAny<decimal>()))
            .ThrowsAsync(new TimeoutException("Gateway timeout"));

        Func<Task> act = () => _service.CheckoutAsync(CustomerId, new[] { Keyboard });

        await act.Should().ThrowAsync<TimeoutException>().WithMessage("Gateway timeout");
        _orders.Verify(orders => orders.SaveAsync(It.IsAny<Order>()), Times.Never);
        _notifications.Verify(notifications => notifications.SendOrderConfirmationAsync(It.IsAny<Order>()), Times.Never);
    }

    // ---------- Helpers ----------

    private void GivenAllProductsInStock() =>
        _inventory
            .Setup(inventory => inventory.HasStockAsync(It.IsAny<Guid>(), It.IsAny<int>()))
            .ReturnsAsync(true);

    private void GivenPaymentSucceeds(bool succeeds) =>
        _payment
            .Setup(payment => payment.ChargeAsync(It.IsAny<Guid>(), It.IsAny<decimal>()))
            .ReturnsAsync(succeeds);

    private void VerifyNoExternalCallsWereMade()
    {
        _inventory.Verify(inventory => inventory.HasStockAsync(It.IsAny<Guid>(), It.IsAny<int>()), Times.Never);
        _payment.Verify(payment => payment.ChargeAsync(It.IsAny<Guid>(), It.IsAny<decimal>()), Times.Never);
        _orders.Verify(orders => orders.SaveAsync(It.IsAny<Order>()), Times.Never);
        _notifications.Verify(notifications => notifications.SendOrderConfirmationAsync(It.IsAny<Order>()), Times.Never);
    }
}
